<?php

use Drupal\SwsDrush\Helpers\EnvironmentDetector;

// When the encryption environment variable is not provided (local/ci/etc),
// fake the encryption string so that the site doesn't break.
if (!getenv('STANFORD_ENCRYPT')) {
  putenv("STANFORD_ENCRYPT=" . substr(file_get_contents("$repo_root/salt.txt"), 0, 32));
}

// Modify the deployment identifier string to help with drupal core cache
// invalidation when deploying to Acquia's server. This helps when the Drupal
// container cache hasn't been cleared yet and during deployment the path
// changes from `01live` to `01liveup` and back. On non-Acquia environments, the
// getAhFilesRoot is just `/mnt/gfs/` so it doesn't affect any local or CI envs.
$settings['deployment_identifier'] = $settings['deployment_identifier'] . '-' . substr(md5(EnvironmentDetector::getAhFilesRoot()), 0, 6);

/**
 * @file
 * Generated by BLT. Serves as an example of global includes.
 */

$settings['file_temp_path'] = '/tmp';

// If this is changed, be sure to change it in the
// factory-hooks/post-settings-php/includes.php file
$settings['config_sync_directory'] = $repo_root . "/docroot/profiles/custom/stanford_profile/config/sync";

//$settings['stanford_capture_ownership'] = EnvironmentDetector::isProdEnv();

if (EnvironmentDetector::isAhEnv()) {
//  $config['config_split.config_split.acsf']['status'] = TRUE;
//  $config['simple_oauth.settings']['public_key'] = EnvironmentDetector::getAhFilesRoot() . '/nobackup/oauth/oauth_public.key';
//  $config['simple_oauth.settings']['private_key'] = EnvironmentDetector::getAhFilesRoot() . '/nobackup/oauth/oauth_private.key';

  // Lock the UI to read_only when on production or test in Acquia.
  if (
    (EnvironmentDetector::isProdEnv() || EnvironmentDetector::isStageEnv())
    && PHP_SAPI !== 'cli'
  ) {
    $settings['config_readonly'] = TRUE;
    $settings['config_readonly_whitelist_patterns'] = [
      'core.menu.static_menu_link_overrides',
      'google_tag.container.*',
      'google_tag.settings',
      'next.next_entity_type_config.*',
      'next.next_site.*',
      'samlauth.authentication',
      'system.action.user_add_role_action.*',
      'system.action.user_remove_role_action.*',
      'system.menu.*',
      'system.theme',
      'user.role.*',
    ];
    $settings['config_readonly_content_link_providers'] = [
      'menu_link_content',
      'menu_link',
    ];
  }
}

// Block the bots when not on production.
if (!EnvironmentDetector::isProdEnv()) {
  $settings['nobots'] = TRUE;
  $config['next.settings']['debug'] = TRUE;
}

// The shared sws-drush-commands logging.settings.php sets error_reporting to
// E_ALL on local/dev, which surfaces PHP 8.4's new implicit-nullable-param
// deprecations from contrib modules with no upstream fix yet. Keep every
// other error type visible, just drop the deprecation noise.
if (EnvironmentDetector::isLocalEnv() || EnvironmentDetector::isDevEnv()) {
  error_reporting(E_ALL & ~E_DEPRECATED);
}

/**
 * Include settings files in docroot/sites/settings.
 *
 * If instead you want to add settings to a specific site, see BLT's includes
 * file in docroot/sites/{site-name}/settings/default.includes.settings.php.
 */
$additionalSettingsFiles = [
  __DIR__ . '/configpages.settings.php',
  __DIR__ . '/environment_indicator.settings.php',
  __DIR__ . '/fast404.settings.php',
  __DIR__ . '/google_analytics.settings.php',
  __DIR__ . '/saml.settings.php',
  __DIR__ . '/xmlsitemap.settings.php',
  "$repo_root/keys/secrets.settings.php",
  EnvironmentDetector::getAhFilesRoot() . "/nobackup/sites/$site_name/secrets.settings.php",
];

foreach ($additionalSettingsFiles as $settingsFile) {
  if (file_exists($settingsFile)) {
    require $settingsFile;
  }
}

if (file_exists(__DIR__ . '/local.settings.php')) {
  require __DIR__ . '/local.settings.php';
}
