
version: 1.3.0
services:
  - composer:
      version: 2
  - php:
      version: 8.1
events:
  build:
    steps:
      - build-soegryphon:
          type: script
          script:
            - 'composer install --no-dev --no-interaction --optimize-autoloader'

